module OrdersHelper

	def us_states
    [
      ['', ''],	
      ['Alabama', '1'],
      ['Alaska', '2'],
      ['Arizona', '3'],
      ['Arkansas', '4'],
      ['California', '5'],
      ['Colorado', '6'],
      ['Connecticut', '7'],
      ['Delaware', '8'],
      ['District of Columbia', '9'],
      ['Florida', '10'],
      ['Georgia', '11'],
      ['Hawaii', '12'],
      ['Idaho', '13'],
      ['Illinois', '14'],
      ['Indiana', '15'],
      ['Iowa', '16'],
      ['Kansas', '17'],
      ['Kentucky', '18'],
      ['Louisiana', '19'],
      ['Maine', '20'],
      ['Maryland', '21'],
      ['Massachusetts', '22'],
      ['Michigan', '23'],
      ['Minnesota', '24'],
      ['Mississippi', '25'],
      ['Missouri', '0'],
      ['Montana', '26'],
      ['Nebraska', '27'],
      ['Nevada', '28'],
      ['New Hampshire', '29'],
      ['New Jersey', '30'],
      ['New Mexico', '31'],
      ['New York', '32'],
      ['North Carolina', '33'],
      ['North Dakota', '34'],
      ['Ohio', '35'],
      ['Oklahoma', '36'],
      ['Oregon', '37'],
      ['Pennsylvania', '38'],
      ['Puerto Rico', '39'],
      ['Rhode Island', '40'],
      ['South Carolina', '41'],
      ['South Dakota', '42'],
      ['Tennessee', '43'],
      ['Texas', '44'],
      ['Utah', '45'],
      ['Vermont', '46'],
      ['Virginia', '47'],
      ['Washington', '48'],
      ['West Virginia', '49'],
      ['Wisconsin', '50'],
      ['Wyoming', '51']
    ]
end
end
